import type { Currency, LiveRate } from "../types/currency";

const COUNTRY_CODE: Record<string, string> = {
  AED: "AE",
  ARS: "AR",
  AUD: "AU",
  BDT: "BD",
  BGN: "BG",
  BHD: "BH",
  BRL: "BR",
  CAD: "CA",
  CHF: "CH",
  CLP: "CL",
  CNY: "CN",
  COP: "CO",
  CZK: "CZ",
  DKK: "DK",
  EGP: "EG",
  EUR: "EU",
  GBP: "GB",
  HKD: "HK",
  HNL: "HN",
  HUF: "HU",
  IDR: "ID",
  INR: "IN",
  ISK: "IS",
  JOD: "JO",
  JPY: "JP",
  KES: "KE",
  KRW: "KR",
  KWD: "KW",
  LBP: "LB",
  LKR: "LK",
  MAD: "MA",
  MXN: "MX",
  MYR: "MY",
  NGN: "NG",
  NOK: "NO",
  NPR: "NP",
  NZD: "NZ",
  OMR: "OM",
  PEN: "PE",
  PHP: "PH",
  PKR: "PK",
  PLN: "PL",
  QAR: "QA",
  RON: "RO",
  RUB: "RU",
  SAR: "SA",
  SEK: "SE",
  SGD: "SG",
  THB: "TH",
  TRY: "TR",
  TWD: "TW",
  UAH: "UA",
  USD: "US",
  VND: "VN",
  ZAR: "ZA",
};

const flagModules = import.meta.glob<string>("../assets/images/flags/*.webp", {
  eager: true,
  import: "default",
});

const flag = (code: string) => {
  const countryCode = COUNTRY_CODE[code].toLowerCase();
  const key = `../assets/images/flags/${countryCode}.webp`;
  const url = flagModules[key];
  if (!url) {
    throw new Error(`Missing flag image for currency code: ${code}`);
  }
  return url;
};

export const CURRENCIES: Currency[] = [
  { code: "USD", name: "US Dollar", flag: flag("USD") },
  { code: "EUR", name: "Euro", flag: flag("EUR") },
  { code: "GBP", name: "British Pound", flag: flag("GBP") },
  { code: "AED", name: "UAE Dirham", flag: flag("AED") },
  { code: "ARS", name: "Argentine Peso", flag: flag("ARS") },
  { code: "AUD", name: "Australian Dollar", flag: flag("AUD") },
  { code: "BDT", name: "Bangladeshi Taka", flag: flag("BDT") },
  { code: "BGN", name: "Bulgarian Lev", flag: flag("BGN") },
  { code: "BHD", name: "Bahraini Dinar", flag: flag("BHD") },
  { code: "BRL", name: "Brazilian Real", flag: flag("BRL") },
  { code: "CAD", name: "Canadian Dollar", flag: flag("CAD") },
  { code: "CHF", name: "Swiss Franc", flag: flag("CHF") },
  { code: "CLP", name: "Chilean Peso", flag: flag("CLP") },
  { code: "CNY", name: "Chinese Yuan", flag: flag("CNY") },
  { code: "COP", name: "Colombian Peso", flag: flag("COP") },
  { code: "CZK", name: "Czech Koruna", flag: flag("CZK") },
  { code: "DKK", name: "Danish Krone", flag: flag("DKK") },
  { code: "EGP", name: "Egyptian Pound", flag: flag("EGP") },
  { code: "HKD", name: "Hong Kong Dollar", flag: flag("HKD") },
  { code: "HNL", name: "Honduran Lempira", flag: flag("HNL") },
  { code: "HUF", name: "Hungarian Forint", flag: flag("HUF") },
  { code: "IDR", name: "Indonesian Rupiah", flag: flag("IDR") },
  { code: "INR", name: "Indian Rupee", flag: flag("INR") },
  { code: "ISK", name: "Icelandic Krona", flag: flag("ISK") },
  { code: "JOD", name: "Jordanian Dinar", flag: flag("JOD") },
  { code: "JPY", name: "Japanese Yen", flag: flag("JPY") },
  { code: "KES", name: "Kenyan Shilling", flag: flag("KES") },
  { code: "KRW", name: "South Korean Won", flag: flag("KRW") },
  { code: "KWD", name: "Kuwaiti Dinar", flag: flag("KWD") },
  { code: "LBP", name: "Lebanese Pound", flag: flag("LBP") },
  { code: "LKR", name: "Sri Lankan Rupee", flag: flag("LKR") },
  { code: "MAD", name: "Moroccan Dirham", flag: flag("MAD") },
  { code: "MXN", name: "Mexican Peso", flag: flag("MXN") },
  { code: "MYR", name: "Malaysian Ringgit", flag: flag("MYR") },
  { code: "NGN", name: "Nigerian Naira", flag: flag("NGN") },
  { code: "NOK", name: "Norwegian Krone", flag: flag("NOK") },
  { code: "NPR", name: "Nepalese Rupee", flag: flag("NPR") },
  { code: "NZD", name: "New Zealand Dollar", flag: flag("NZD") },
  { code: "OMR", name: "Omani Rial", flag: flag("OMR") },
  { code: "PEN", name: "Peruvian Sol", flag: flag("PEN") },
  { code: "PHP", name: "Philippine Peso", flag: flag("PHP") },
  { code: "PKR", name: "Pakistani Rupee", flag: flag("PKR") },
  { code: "PLN", name: "Polish Zloty", flag: flag("PLN") },
  { code: "QAR", name: "Qatari Riyal", flag: flag("QAR") },
  { code: "RON", name: "Romanian Leu", flag: flag("RON") },
  { code: "RUB", name: "Russian Ruble", flag: flag("RUB") },
  { code: "SAR", name: "Saudi Riyal", flag: flag("SAR") },
  { code: "SEK", name: "Swedish Krona", flag: flag("SEK") },
  { code: "SGD", name: "Singapore Dollar", flag: flag("SGD") },
  { code: "THB", name: "Thai Baht", flag: flag("THB") },
  { code: "TRY", name: "Turkish Lira", flag: flag("TRY") },
  { code: "TWD", name: "Taiwan Dollar", flag: flag("TWD") },
  { code: "UAH", name: "Ukrainian Hryvnia", flag: flag("UAH") },
  { code: "VND", name: "Vietnamese Dong", flag: flag("VND") },
  { code: "ZAR", name: "South African Rand", flag: flag("ZAR") },
];

export const LIVE_RATES: LiveRate[] = [
  { pair: "EUR/USD", value: "1.1723", change: "-0.14%", direction: "down" },
  { pair: "USD/JPY", value: "157.91", change: "+0.04%", direction: "up" },
  { pair: "GBP/USD", value: "1.3575", change: "-0.22%", direction: "down" },
  { pair: "USD/CHF", value: "0.9098", change: "+0.13%", direction: "up" },
  { pair: "EUR/GBP", value: "0.8633", change: "+0.11%", direction: "up" },
  { pair: "AUD/USD", value: "0.7208", change: "+0.08%", direction: "up" },
  { pair: "USD/CAD", value: "1.3815", change: "+0.04%", direction: "up" },
];

export const DEFAULT_FROM = "USD";
export const DEFAULT_TO = "EUR";
